name: Code Quality Check

on: [push, pull_request] # プッシュかプルリクを送ると起動

jobs:
  lint-and-test:
    runs-on: ubuntu-latest # GitHubが貸してくれるLinuxマシンで実行
    steps:
      - uses: actions/checkout@v4 # コードをコピー

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Node.jsのバージョン指定

      - name: Install dependencies
        run: npm install # ライブラリをインストール

      - name: Run Lint
        run: npm run lint # コードの書き間違いチェックを実行

      - name: Run Test
        run: echo "No tests to run"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.NYRRR_ACTIONS_TOKEN }}
          vercel-org-id: ${{ secrets.team_9jK8CZ14XKIBkwZuDBBVoAxJ }}
          vercel-project-id: ${{ secrets.prj_O3cnfIjvOVec0jn2WFBnN73dhvWH }}
          vercel-args: '--prod --yes'
